### PR TITLE
fix memory leak when alloc new data failed

### PR DESCRIPTION
**Pull request by Cherisher**

### CODE REVIEW

**Comment by xiaokai-wang** [comment]
@Cherisher thanks.

**Comment by gfrankliu** [comment]
@xiaokai-wang Do we need similar fixes in https://github.com/xiaokai-wang/nginx-stream-upsync-module ?

**Comment by xiaokai-wang** [comment]
@gfrankliu yes, I think so.
@Cherisher Can you sync the changes to the module [nginx-stream-upsync-module](https://github.com/xiaokai-wang/nginx-stream-upsync-module). Thanks.

**Comment by Cherisher** [comment]
Finish pull request sync

**Pull request merged**
